name: rust checks

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./rust

jobs:
  verify-formatting:
    name: verify formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check

  verify-compilability:
    name: verify compilability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --all
